#!/bin/bash
for ((a=3991 ; a<=4042 ; a++)) 
do 
echo -n "
vlan $a
name ipoe$a"
#echo -n "interface bundle-ether 1.4094$a l2transport
#encapsulation dot1q 4094 second-dot1q $a
#rewrite ingress tag pop 2 symmetric 
#" 
done
