#!/bin/bash
for ((a=2201 ; a<=2600 ; a++)) 
do 
echo -n "
configure l2vpn vpls vpls-$a add service vman IPOE$a
"

#echo -n "interface bundle-ether 1.4094$a l2transport
#encapsulation dot1q 4094 second-dot1q $a
#rewrite ingress tag pop 2 symmetric 
 
done
